platform :ios, '7.0'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'YTKNetwork'
pod 'SVProgressHUD'
pod 'LBXScan',:git=>'https://github.com/MxABC/LBXScan.git'
pod 'jastor'
pod 'BeeCloud'
pod 'SDCycleScrollView'